### ISSUE TITLE
new representation to add?

### ISSUE THREAD

**Issue by amphilli** [mjohnson11/Yoda_viz#11]
this one uses the opposite weights as the current layout, so its more useful for visualizing pathways (things are close if that mutation improves binding)--there is this island detached from everything that has decent breadth but appears separated from the rest of the pathway. i'm having trouble figuring out what these genotypes are & figured your browser might enable us to do this! let me know if i can provide a better format to make things easier,thx!

[umap_pathways_9114.txt](https://github.com/mjohnson11/Yoda_viz/files/6079764/umap_pathways_9114.txt)

**Comment by mjohnson11** [comment]
This was formatted exactly like the other one, so it was easy to add it! Live at https://xenodochial-heyrovsky-a2556e.netlify.app/new_weighting.html ! (in https://github.com/mjohnson11/Yoda_viz/commit/94ccbab79af38ac098d816d79a8924bc6a3669b6)

**Comment by mjohnson11** [comment]
(would be better to have it as an option on the same page, but was easier to just make another page for now)
