### ISSUE TITLE
potential curve improvements

### ISSUE THREAD

**Issue by amphilli** [mjohnson11/Yoda_viz#13]
would be cool to have the variant binary string as the plot title, and if it can handle plotting error bars those would also be useful! y-axis would be ‘mean bin’, x-axis is '-log[HA], M', with these tick values:

H1: (-14, -12, -11.5, -11, -10.5, -10, -9.5, -9, -8.5,-8, -7.5, -7)
H3/FLUB: (-14, -11, -10.5, -10, -9.5, -9, -8.5,-8, -7.5, -7, -6.5, -6)

**Comment by mjohnson11** [comment]
addressed in https://github.com/mjohnson11/Yoda_viz/commit/88c73395281734970aa99304cfdb94e4bace6f0d
