### ISSUE TITLE
request from reviewer

### ISSUE THREAD

**Issue by amphilli** [mjohnson11/Yoda_viz#16]
in violin plots, is it possible to toggle between displaying as 0/1 and displaying as the amino acids? alternatively, could just add an explanation as to which amino acid corresponds to zero and one.

**Comment by mjohnson11** [comment]
Finally got around to this! in https://github.com/mjohnson11/Yoda_viz/commit/1a3a724f7ba563ccc2eefa62a3961046c929abc3
