### ISSUE TITLE
curves disappeared :/

### ISSUE THREAD

**Issue by amphilli** [mjohnson11/Yoda_viz#17]
Hi Milo! The package were using the load the data got updated and now the curves don't show up -- do you mind replacing the following lines of code in the html file when you have a chance:

`<script src="https://cdn.jsdelivr.net/npm/arquero@4"></script>` should replace
`<script src="https://cdn.jsdelivr.net/npm/arquero@latest"></script>` in index.html

**Comment by mjohnson11** [comment]
Thanks for the specifics, easy fix! I'm going to try to add you as a collaborator on this project so you can push quick changes like this too - I haven't done this before on github so hopefully it will work!
