### ISSUE TITLE
highlight somatic and germline dots

### ISSUE THREAD

**Issue by klawrence26** [mjohnson11/Yoda_viz#4]
It would be great to have the germline (all 0) and somatic (all 1) sequences highlighted somehow, on the center map and/or the phenotype distribution -- maybe a different marker shape/size or color? We sometimes have used stars or something like that drawn on top of the other dots

**Comment by mjohnson11** [comment]
I've added little diamond markers on the center map, though they aren't hoverable and connected to the phenotype distribution, which might be important. But for now, there are some markers to at least show where they are in the fdl space. I had a hard time choosing colors - eventually went with red and blue, but that could change

**Comment by mjohnson11** [comment]
Now that I'm thinking about this (after I added the markers of course...) I think annotation with a line pointing out where each is would be better. What would be good labels - "germline" and "somatic"? Anything shorter like "WT" and ???

**Comment by klawrence26** [comment]
Mm maybe "GL" and "S"? or "WT" and "S"? not super intuitive i guess...

**Comment by mjohnson11** [comment]
For now I did annotations with "Germline" and "Somatic" - there's room for the full words, why not! https://github.com/mjohnson11/Yoda_viz/commit/4aae26649dc73fe4aa61f97f9042fefad32a3d29
